[workspace]
resolver = "2"

members = [
    "crates/*"
]

# these patches come from the root workspace Cargo.toml [patch.crates-io] of the namada repo
[patch.crates-io]
borsh = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-schema-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}

[patch."https://github.com/anoma/namada"]
# specify the specific version of Namada being worked against here
# https://stackoverflow.com/a/72261235/2387626
namada = {git = "https://github.com/anoma/namada?rev=v0.7.1"}